# Generated by Django 4.2 on 2024-10-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_productrating_email_productrating_created_at_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites_product',
            field=models.ManyToManyField(to='market.product'),
        ),
    ]
